name: integration

on: [pull_request]
#on:
#  pull_request:
#    branches:
#      - dev

jobs:
  integration:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1.2
        with:
          working-directory: ./ #optional
          run: npm test
      - name: Install
        run: npm ci
      - name: Test
        run: npm run 