# Source for release action https://github.com/samuelmeuli/action-electron-builder
# See README on use

name: release

on:
  push:
    branches:
      - master

jobs:
  tagger:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      output1: ${{ steps.setoutput.outputs.release }}
      
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: '0'
        
    - name: get package version
      # this will get use the version number in package.json in the format vx.x.x
      run: echo "::set-env name=PACKAGE_VER::$(cat package.json | grep version | head -1 | awk '{print $2}' | sed 's/[\",]//g' | perl -ne 'print "v$_"')"
    
    - name: check for existing tags
      # this will check if master has any tags with the pulled version in the format vx.x.x
      run: echo "::set-env name=NEW_VERSION::$(git tag -l ${{env.PACKAGE_VER}})"  
      
    - id: setoutput
      # here is how we trigger the build commands to run - this passes a boolean to our build_and_release job
      if: ${{!contains(env.NEW_VERSION, env.PACKAGE_VER)}}
      run: echo "::set-output name=release::true"
      
    - name: Bump version and push tag
      # if we do have a new release then we tag the repo with the line vx.x.x that we pulled earlier
      if: ${{!contains(env.NEW_VERSION, env.PACKAGE_VER)}}
      uses: anothrNick/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_BRANCHES : master
        CUSTOM_TAG: ${{env.PACKAGE_VER}}
    
    
  build_and_release:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    needs: tagger
    if: ${{needs.tagger.outputs.output1}}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1

      - name: Build and Release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: true
